# THIS FILE IS AUTOMATICALLY GENERATED.
# Disclaimer: Please test this file before using in production.
"""
Generated blueprint DSL (.py)
"""

import json  # no_qa
import os  # no_qa

from calm.dsl.builtins import CalmTask as CalmVarTask
from calm.dsl.builtins import *  # no_qa
from calm.dsl.runbooks import CalmEndpoint as Endpoint

# Secret Variables

BP_CRED_work_PASSWORD = read_local_file("BP_CRED_work_PASSWORD")

# Credentials
BP_CRED_work = basic_cred(
    "root",
    BP_CRED_work_PASSWORD,
    name="work",
    type="PASSWORD",
    default=True,
)


class Service1(Service):

    pass


class vmcalm_array_indexcalm_timeResources(AhvVmResources):

    memory = 1
    vCPUs = 1
    cores_per_vCPU = 1
    disks = [
        AhvVmDisk.Disk.Scsi.cloneFromImageService(
            "Centos7HadoopMaster.qcow2", bootable=True
        )
    ]
    nics = [
        AhvVmNic.NormalNic.ingress(
            "vlan.0", cluster="auto_cluster_nested_69f8deca7298f608a8123fbe"
        )
    ]

    power_state = "ON"
    boot_type = "LEGACY"


class vmcalm_array_indexcalm_time(AhvVm):

    name = "vm-@@{calm_array_index}@@-@@{calm_time}@@"
    resources = vmcalm_array_indexcalm_timeResources
    cluster = Ref.Cluster(name="auto_cluster_nested_69f8deca7298f608a8123fbe")


class VM1(Substrate):

    account = Ref.Account("NTNX_LOCAL_AZ")
    os_type = "Linux"
    provider_type = "AHV_VM"
    provider_spec = vmcalm_array_indexcalm_time

    readiness_probe = readiness_probe(
        connection_type="SSH",
        disabled=True,
        retries="3",
        connection_port=22,
        address="@@{platform.status.resources.nic_list[0].ip_endpoint_list[0].ip}@@",
        delay_secs="10",
        credential=ref(BP_CRED_work),
    )


class Package1(Package):

    services = [ref(Service1)]


class deployment_f0237565(Deployment):

    min_replicas = "1"
    max_replicas = "1"
    default_replicas = "1"

    packages = [ref(Package1)]
    substrate = ref(VM1)


class Default(Profile):

    environments = [Ref.Environment(name="work")]
    deployments = [deployment_f0237565]

    custom_form = CustomForm(name="custom_form_751ebecf-106e-3b0d-66e8-51d07ff92983")
    use_custom_form = False


class bp_cf(Blueprint):

    services = [Service1]
    packages = [Package1]
    substrates = [VM1]
    profiles = [Default]
    credentials = [BP_CRED_work]


class BpMetadata(Metadata):

    project = Ref.Project("setup")
